### ISSUE TITLE
Crash on eat if damage disabled and hbhunger mod loaded

### ISSUE THREAD

**Issue by bell07** [tenplus1/pie#2]
If damage is disabled in a world but thte game have hbhunger mod the game crashed with 
`Undeclared global variable "hbhunger" accessed at ....minetest/games/whynot-git/mods/food/pie/init.lua:45`

My proposed solution is to check globals instead of mod paths

```
-local hmod = minetest.get_modpath("hunger")
-local hbmod = minetest.get_modpath("hbhunger")
-local stmod = minetest.get_modpath("stamina")
+local hmod = minetest.global_exists("hunger")
+local hbmod = minetest.global_exists("hbhunger")
+local stmod = minetest.global_exists("stamina")

```
tested with hbhunger and works for me

**Comment by tenplus1** [comment]
fixed, thanks :)
